# Generated by Django 4.0.8 on 2022-10-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanantes',
            fields=[
                ('idacompanantes', models.AutoField(db_column='idAcompanantes', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('apellidos', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('identificacion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'Acompanantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artefactos',
            fields=[
                ('idartefactos', models.AutoField(db_column='idArtefactos', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('tamano', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=30, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Artefactos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('idboleta', models.AutoField(db_column='idBoleta', primary_key=True, serialize=False)),
                ('mediodepago', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='medioDePago', max_length=15, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('banco', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('comprobante', models.BinaryField(blank=True, max_length='max', null=True)),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idcomuna', models.AutoField(db_column='idComuna', primary_key=True, serialize=False)),
                ('comuna', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('iddepartamento', models.AutoField(db_column='idDepartamento', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('canthabitaciones', models.IntegerField(blank=True, db_column='cantHabitaciones', null=True)),
                ('cantbanos', models.IntegerField(blank=True, db_column='cantBanos', null=True)),
                ('precionoche', models.IntegerField(blank=True, db_column='precioNoche', null=True)),
                ('fechaestadodepto', models.DateField(blank=True, db_column='fechaEstadoDepto', null=True)),
            ],
            options={
                'db_table': 'Departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleinconveniente',
            fields=[
                ('iddetalleinconveniente', models.AutoField(db_column='idDetalleInconveniente', primary_key=True, serialize=False)),
                ('detalle', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=200, null=True)),
                ('monto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DetalleInconveniente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleservicio',
            fields=[
                ('iddetalleservicio', models.AutoField(db_column='idDetalleServicio', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('montototal', models.IntegerField(blank=True, db_column='montoTotal', null=True)),
            ],
            options={
                'db_table': 'DetalleServicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='Modern_Spanish_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='Modern_Spanish_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadodepto',
            fields=[
                ('idestadodepto', models.AutoField(db_column='idEstadoDepto', primary_key=True, serialize=False)),
                ('estadodepto', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='estadoDepto', max_length=50)),
            ],
            options={
                'db_table': 'EstadoDepto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('idgaleria', models.AutoField(db_column='idGaleria', primary_key=True, serialize=False)),
                ('imagen', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'Galeria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('idgastos', models.AutoField(db_column='idGastos', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=15, null=True)),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('fechagastos', models.DateField(blank=True, db_column='fechaGastos', null=True)),
            ],
            options={
                'db_table': 'Gastos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idinventario', models.AutoField(db_column='idInventario', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idregion', models.AutoField(db_column='idRegion', primary_key=True, serialize=False)),
                ('region', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('idreserva', models.AutoField(db_column='idReserva', primary_key=True, serialize=False)),
                ('fechadesde', models.DateField(blank=True, db_column='fechaDesde', null=True)),
                ('fechahasta', models.DateField(blank=True, db_column='fechaHasta', null=True)),
                ('estadoreserva', models.BooleanField(blank=True, db_column='estadoReserva', null=True)),
                ('abono', models.IntegerField(blank=True, null=True)),
                ('checkin', models.DateTimeField(blank=True, db_column='checkIn', null=True)),
                ('chekout', models.DateTimeField(blank=True, db_column='chekOut', null=True)),
                ('fechahorareserva', models.DateTimeField(blank=True, db_column='fechaHoraReserva', null=True)),
                ('precionochereserva', models.IntegerField(blank=True, db_column='precioNocheReserva', null=True)),
                ('saldo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Reservas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('idservicio', models.AutoField(db_column='idServicio', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
                ('disponibilidad', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=13, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipogasto',
            fields=[
                ('idtipogasto', models.AutoField(db_column='idTipoGasto', primary_key=True, serialize=False)),
                ('tipogasto', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='tipoGasto', max_length=50, null=True)),
            ],
            options={
                'db_table': 'TipoGasto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposervicios',
            fields=[
                ('idtiposervicio', models.AutoField(db_column='idTipoServicio', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=100, null=True)),
            ],
            options={
                'db_table': 'TipoServicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipousuarios',
            fields=[
                ('idtipousuario', models.AutoField(db_column='idTipoUsuario', primary_key=True, serialize=False)),
                ('tipousuario', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='tipoUsuario', max_length=50)),
            ],
            options={
                'db_table': 'TipoUsuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('apellidos', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50)),
                ('usuario', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True, unique=True)),
                ('correo', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=40, unique=True)),
                ('contrasena', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=500)),
                ('identificacion', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=9, unique=True)),
                ('celular', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=50, unique=True)),
                ('pais', models.CharField(db_collation='Modern_Spanish_CI_AS', max_length=100)),
                ('codigoverificacion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='codigoVerificacion', max_length=15, null=True)),
                ('habilitada', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=13, null=True)),
                ('espasaporte', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='esPasaporte', max_length=9, null=True)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
    ]
